services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - LUNCH_CHANNEL_EMAIL_ADDRESS
      - LUNCH_DAY_OF_WEEK
      - LUNCH_HOUR
      - LUNCH_MINUTES
      - TZ
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD
      - SMTP_FROM
